Updated yaml to read env variables

diff --git a/.github/workflows/node.js.yml b/.github/workflows/node.js.yml
--- a/.github/workflows/node.js.yml
+++ b/.github/workflows/node.js.yml
@@ -1,26 +1,18 @@
-# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
-# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
-
 name: Functional Tests
 
 on:
   push:
     branches: [ "main" ]
   schedule:
-    - cron: '0 7 * * *'  # Runs at 7:00 AM UTC every day
-
+    - cron: '0 7 * * *'
 
 jobs:
   build:
-
     runs-on: ubuntu-latest
-
-      
 
     strategy:
       matrix:
         node-version: [18.x, 20.x, 22.x]
-        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
 
     steps:
     - uses: actions/checkout@v4
@@ -31,7 +23,24 @@ jobs:
         cache: 'npm'
     - run: npm ci
     - run: npm run build --if-present
-    - run: npm test
+
+    # Optional: Early fail if any required env is missing
+    - name: Check required environment variables
+      run: |
+        for var in STANDARD_USER LOCKED_OUT_USER PASSWORD API_KEY; do
+          if [ -z "${!var}" ]; then
+            echo "$var is not set"
+            exit 1
+          fi
+        done
+      env:
+        STANDARD_USER: ${{ vars.STANDARD_USER }}
+        LOCKED_OUT_USER: ${{ vars.LOCKED_OUT_USER }}
+        PASSWORD: ${{ secrets.PASSWORD }}
+        API_KEY: ${{ secrets.API_KEY }}
+
+    - name: Run tests
+      run: npm test
       env:
         STANDARD_USER: ${{ vars.STANDARD_USER }}
         LOCKED_OUT_USER: ${{ vars.LOCKED_OUT_USER }}
